language: java
jdk:
- openjdk8
after_success:
- bash <(curl -s https://codecov.io/bash)
branches:
  only:
  - master
  - "/^v\\d{1}\\.\\d{1,2}.\\d{1,2}$/"
notifications:
  email:
    recipients:
    - hi@xuyuanxiang.cn
    on_success: never
    on_failure: always
